Website text adaptation
w3c/wot-cg pull request #145
Opened 2024-03-14 11:10 UTC by Tedoshiii

- Adapted "What is WoT" and "Payloads and Headers" pages on the website for better readability
- Added relevant diagrams and images

2024-03-15 09:45 UTC, egekorkan requested changes

2024-03-15 09:45 UTC, egekorkan commented on Tutorials/whatiswot/2-Payloads_and_Headers/2-Payloads_and_Headers.txt
> +There are different payload types such as  JSON, XML, CBOR, Text,Audio and Video and more.
```suggestion
There are different payload types such as  JSON, XML, CBOR, Text, Audio and Video and more.
```

2024-03-15 09:45 UTC, egekorkan commented on Tutorials/whatiswot/website/docs/intro.md
> +To gain a grasp on the meaning of the Web of Things, it's important to first understand what the difference between WoT and IoT (Internet of Things) is. While IoT focuses on technologies for connecti
```suggestion
To gain a grasp on the meaning of the Web of Things, it's important to first understand what the difference between WoT and IoT is. While IoT focuses on technologies for connecting devices to the Internet, WoT takes it a step further. It builds on IoT by making sure all these connected devices can work together seamlessly. This interoperability is achieved using established architectural ideas for the Web and web technologies.
```

2024-03-15 09:45 UTC, egekorkan commented on Tutorials/whatiswot/website/docs/Payloads and Headers.md
For the examples below, separate them into a new section. Also adding a human-readable introduction that explains what the data is would be nice

2024-04-04 19:28 UTC, egekorkan requested changes

2024-04-04 19:28 UTC, egekorkan commented on Tutorials/whatiswot/website/docs/Payloads and Headers.md
> +In the Web of Things, the smart devices are constantly exchanging a lot of data. Such data is sent via payloads, therefore it is essential to understand what are payloads and headers that describe th
```suggestion
In the Web of Things, smart devices typically exchange data with each other. Such data is sent via payloads, therefore it is essential to understand what payloads are and the headers that describe them. Thus, in this section, we will cover the topics of headers and the different types of payloads - including JSON, the most used one in the scope of WoT, and its importance.
```

2024-04-04 19:28 UTC, egekorkan commented on Tutorials/whatiswot/website/docs/Payloads and Headers.md
> +So let us show you an example of a **JSON payload**.
In cases where we show code or json, we should not put an image but simply keep the code with correct highlighting

2024-04-04 19:28 UTC, egekorkan commented
Another general point: Please split this amount of input into multiple PRs. It is just quicker to review and get quicker feedback :)

2024-04-14 03:00 UTC, Tedoshiii commented
- Applied latest feedback.
- Added missing information from the JSON Introduction page.

PR is ready to be merged and any additional changes will be handled in a separate one.

2024-04-14 12:06 UTC, merged