8th tutorial video review
w3c/wot-cg pull request #166
Opened 2024-07-11 00:45 UTC by Tedoshiii

- Please use the following link for reviews: https://murf.ai/share/lmxpv0ix
- Applied the requested fixes mentioned in issue #152

2024-07-11 21:07 UTC, TallTed commented
Things get renumbered. Far better to refer to the full video title than to its potentially variable position in a list.

2024-07-11 21:12 UTC, TallTed requested changes
Small, editorial

2024-07-11 21:12 UTC, TallTed commented on Tutorials/whatiswot/8-JSON_Schema_in_Practice_3/8-JSON-Schema-3.txt
> +Throughout this video, we will mainly focus on validation with the Python library jsonschema and the JavaScript library AJV, but there are many other libraries in different programming languages and
```suggestion
Throughout this video, our main focus will be on validation with the `jsonschema` Python library and the `AJV` JavaScript library, but many other libraries to validate JSON using a JSON Schema exist in different programming languages and tools. 
```

2024-07-11 21:12 UTC, TallTed commented on Tutorials/whatiswot/8-JSON_Schema_in_Practice_3/8-JSON-Schema-3.txt
> +Here are some of the popular ones in different programming languages. There are many more validators.
```suggestion
There are many validators. Here are some of the more popular ones.  
```

2024-07-11 21:12 UTC, TallTed commented on Tutorials/whatiswot/8-JSON_Schema_in_Practice_3/8-JSON-Schema-3.txt
> +The library takes a schema for your JSON data and validates your data according to the schema. Outputs the validation result as a boolean
```suggestion
The library takes a schema for your JSON data and validates your data according to the schema. The validation result is output as a boolean.
```

2024-07-11 21:12 UTC, TallTed commented on Tutorials/whatiswot/8-JSON_Schema_in_Practice_3/8-JSON-Schema-3.txt
> +First, We are importing the AJV.
```suggestion
First, we import the `AJV` library.  
```

2024-07-12 08:31 UTC, egekorkan commented
@TallTed thank you for the reviews. We just talked about it today and @Tedoshiii will incorporate them.
Otherwise, the original issue is now resolved and I am marking it in #152

2024-07-26 08:10 UTC, egekorkan commented
#169 takes over the changes here

2024-07-26 08:10 UTC, closed without merging