add txt and vtt files for 4th tutorial
w3c/wot-cg pull request #87
Opened 2023-09-08 17:04 UTC by handealptekin

https://murf.ai/share/lm6azmy3

2023-09-24 14:49 UTC, egekorkan requested changes

2023-09-24 14:49 UTC, egekorkan commented on Tutorials/whatiswot/4-JSON_in_Practice/4-JSON-in-Practice.txt
> +In the last video, we showed mostly primitive types of JSON. In this video, we will focus on first arrays and objects, and then we will mention common mistakes when writing JSON. At the end of the vi
```suggestion
In the last video, we showed mostly primitive types of JSON. In this video, we will first focus on arrays and objects, and then we will mention common mistakes when writing JSON. At the end of the video, we will demonstrate the usage of JSON generation and parsing.
```

2023-09-24 14:49 UTC, egekorkan commented on Tutorials/whatiswot/4-JSON_in_Practice/4-JSON-in-Practice.txt
> +Objects start and end with curly brackets. It is basically defining keywords and mapping these keywords to values.
at this time, the arrows are not 90°. Is this intended?

2023-09-24 14:49 UTC, egekorkan commented on Tutorials/whatiswot/4-JSON_in_Practice/4-JSON-in-Practice.txt
> +Also JSON is case sensitive. Thus, "is Active" with upper case A is not the same as “is active” with lower case A.
```suggestion
Also, JSON is case sensitive. Thus, "is Active" with upper case A is not the same as “is active” with lower case A. 
```

2023-09-24 14:49 UTC, egekorkan commented on Tutorials/whatiswot/4-JSON_in_Practice/4-JSON-in-Practice.txt
> +Putting comments inside JSON documents is not valid contrast to most of the programming languages.
```suggestion
Putting comments inside JSON documents is not valid.
```

Since JSON is not a programming language, it is not good to compare.

2023-09-24 14:49 UTC, egekorkan commented on Tutorials/whatiswot/4-JSON_in_Practice/4-JSON-in-Practice.txt
> +Similar to the previous one depending on the programming language that you use syntax might differ.
```suggestion
Similar to the previous one depending on the programming language that you use, syntax might differ.
```

2023-09-24 14:49 UTC, egekorkan commented on Tutorials/whatiswot/4-JSON_in_Practice/4-JSON-in-Practice.txt
> +For example, true false keywords in JSON, Rust, JavaScript, and Golang are written lowercase while in Python the first letter of these keywords needs to be capitalized.
```suggestion
For example, true false keywords in JSON, Rust, JavaScript, and Golang are written lowercase, while in Python the first letter of these keywords needs to be capitalized.
```

2023-09-24 14:49 UTC, egekorkan commented on Tutorials/whatiswot/4-JSON_in_Practice/4-JSON-in-Practice.txt
> +In JSON and JavaScript it is null with lowercase while in Python, the same meaning is given with the "None" keyword.
None pronunciation is very weird

2023-09-24 14:49 UTC, egekorkan commented on Tutorials/whatiswot/4-JSON_in_Practice/4-JSON-in-Practice.txt
> +In the next video, we will talk about JSON Schema.
Before this, there should be some wrapping-up sentences like:

(pause) This concludes the basics of JSON and how to use it. In the next ...

2023-09-25 15:35 UTC, relu91 reviewed
I have more or less the same Ege's remarks just one bit: from minute `3:32` the music stops not sure if it is intended, but it would be better to keep it until the end.

2023-10-01 21:37 UTC, egekorkan commented
> I have more or less the same Ege's remarks just one bit: from minute `3:32` the music stops not sure if it is intended, but it would be better to keep it until the end.

Indeed. If possible, the audio should loop and that finishing sequence should come only at the end.

2023-10-05 19:39 UTC, handealptekin commented
Video has been updated according to the requested changes. You can view it from the same link

2023-10-06 09:33 UTC, egekorkan commented
We will keep it open since the music restarts abruptly at the moment.

2023-10-20 09:53 UTC, egekorkan commented
@handealptekin will fix the music like in 3rd video and push the powerpoint together

2023-10-22 21:36 UTC, handealptekin commented
I applied a fade-in/fade-out where the song ends and the other song begins again. It should be reviewed and decided upon

2023-10-26 14:06 UTC, egekorkan commented
I think it is fine now, I have increased the fade amount as well. @handealptekin could you push the video file as well and then I can merge it.

2023-10-26 14:11 UTC, handealptekin commented
> I think it is fine now, I have increased the fade amount as well. @handealptekin could you push the video file as well and then I can merge it.

Should i push the video with the sound from murf.ai? And if so, should the subtitle be included in the video?

2023-10-27 08:42 UTC, egekorkan commented
The video has been reviewed and can be merged. There will be a change to background music for all videos as mentioned at #114

2023-10-27 08:42 UTC, merged